Update install.md
cortexlabs/cortex pull request #1839
Opened 2021-02-01 16:40 UTC by JackHopkins

It seems that the following two dependencies are no longer in use. They throw an error when explicitly included, and so should probably be removed.

image_statsd: quay.io/cortexlabs/statsd:0.27.0
image_pause: quay.io/cortexlabs/pause:0.27.0

2021-02-01 16:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cortexlabs/cortex?pullRequest=1839) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cortexlabs/cortex?pullRequest=1839) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cortexlabs/cortex?pullRequest=1839) it.</sub>

2021-02-01 17:56 UTC, miguelvr requested changes

2021-02-01 17:56 UTC, miguelvr commented on docs/clusters/gcp/install.md
> -image_statsd: quay.io/cortexlabs/statsd:0.27.0
this one is addressed in master now

2021-02-01 17:56 UTC, miguelvr commented on docs/clusters/gcp/install.md
> -image_pause: quay.io/cortexlabs/pause:0.27.0
this is indeed a mistake but it should instead be replaced by:

`image_google_pause: quay.io/cortexlabs/google-pause:0.27.0`

2021-02-02 22:25 UTC, deliahu approved these changes
@JackHopkins Thanks for fixing this! I pushed a small update to the PR to address @miguelvr's comments, does it look good now to you?

2021-02-09 23:11 UTC, deliahu commented
@JackHopkins the docs have been updated in the latest version (0.28), but we can still merge this into the 0.27 branch. The merging is blocked on the CLA check, do you mind signing it [here](https://cla-assistant.io/cortexlabs/cortex?pullRequest=1839)?

2021-02-23 17:52 UTC, closed without merging

2021-03-25 23:04 UTC, JackHopkins commented
Apologies - have signed!